### PR TITLE
remove npm and node as dependencies

### PR DESCRIPTION
**Pull request by phloe**
When trying to install `bridge-pca` i get an error due to node set as a dependency on a specific version that I'm not using (v16.13.1).

Screenshot 2022-05-15 at 21 01 03

 IFAICT the actual node (and npm) version is irrelevant to the actual package - so I just suggest removing them 🙂

### CODE REVIEW

**Comment by Myndex** [comment]
Doh! Yea they were not supposed to be there as dependencies...

**Comment by Myndex** [comment]
Hey Rasmus @phloe 

I corrected these problems and fixed the module issues —— again thank you so very much for your help, it was just the needed nudge to point me in the right direction — the reason I had been having problems is ultimately how I was initing the variable for the for loops... I picked up that was the problem looking at your other pull request.

All the vrious packages are now using export/import etc, and I own you a debt of gratitude.

Closing this PR, changes made separately.

**Comment by phloe** [comment]
@Myndex 1 note: when importing an npm package you can do it by just referencing the package name.

So in https://github.com/Myndex/bridge-pca/blob/master/src/bridge-pca.js#L133 

```js
import { colorParsley, colorToHex, colorToRGB } from '../node_modules/colorparsley/src/colorparsley.js';
```

you can just write:

```js
import { colorParsley, colorToHex, colorToRGB } from 'colorparsley';
```

🙂

**Comment by Myndex** [comment]
> @Myndex 1 note: when importing an npm package you can do it by just referencing the package name.

Hi @phloe  thank you... I want to say I tried that initially, but that was before I realized my` for (...` loop variables were incorrectly scoped...  doh..

😳

**Pull request closed without merging**
